### PR TITLE
Native libraries for MacOSX

### PR DESCRIPTION
**Pull request by tangzero**
See non2d/non#21

### CODE REVIEW

**Comment by deathbeam** [comment]
Wow that is so awesome, thank you.

**Comment by deathbeam** [comment]
Oh totally forgot. Can you please also test it? Just cd into `template` directory and run
`gradlew desktop:dist`

Then run
`java -jar desktop/build/libs/desktop-1.0.jar`

It should print `Hello world from Lua` to console or something like that.

**Comment by tangzero** [comment]
Works.

```
Hello World from Lua!
```

**Comment by deathbeam** [comment]
Great, thank you.

**Pull request merged**
